on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:


permissions:
  contents: write

jobs:
  create-packages:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JBR
        uses: actions/setup-java@v4
        with:
          distribution: "jetbrains"
          java-package: "jdk"
          java-version: "21"
          check-latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            C:/Users/runneradmin/.gradle/caches
            C:/Users/runneradmin/.gradle/wrapper
          key: windows-2022-gradle
          enableCrossOsArchive: true

      - name: Gradle
        run: |
          ./gradlew.bat

      - name: Build desktop package
        run: |
          ./gradlew.bat :desktop:app:createBinariesForCi

      - name: Release Gradle to unlock cache files
        run: |
          ./gradlew.bat --stop

      - name: Upload output to artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./build/ci-release
          name: app-windows

  release:
    runs-on: "ubuntu-latest"
    needs: [ "create-packages" ]
    steps:
      - uses: "actions/download-artifact@v4"
        name: "Download All Artifacts Into One Directory"
        with:
          path: release
          pattern: app-*
          merge-multiple: true

      - name: Version Info
        id: version
        uses: nowsprinting/check-version-format-action@v3
        with:
          prefix: "v"

      - name: "Show the output tree of release"
        run: |
          tree .
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ !steps.version.outputs.is_stable }}
          make_latest: legacy
          draft: true
          files: |
            release/binaries/*
          body_path: release/release-notes.md
      - name: "Remove artifacts to free space"
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app-*
